export const navigationDb = [
    {
        id: 2,
        idMaster: null,
        idUp: null,
        idDown: 3,
        idLeft: 5,
        idRight: 5,
        idReserve1: null,
        idReserve2: null,
        idReserve3: null,
        p1: null,
        p2: null,
        del: null,
    },
    {
        id: 3,
        idMaster: null,
        idUp: 2,
        idDown: 4,
        idLeft: null,
        idRight: null,
        idReserve1: null,
        idReserve2: null,
        idReserve3: null,
        p1: null,
        p2: null,
        del: null,
    },
    {
        id: 4,
        idMaster: null,
        idUp: 3,
        idDown: null,
        idLeft: null,
        idRight: null,
        idReserve1: null,
        idReserve2: null,
        idReserve3: null,
        p1: null,
        p2: null,
        del: null,
    },
    {
        id: 5,
        idMaster: null,
        idUp: null,
        idDown: null,
        idLeft: 2,
        idRight: 2,
        idReserve1: null,
        idReserve2: null,
        idReserve3: null,
        p1: null,
        p2: null,
        del: null,
    },
    {
        id: null,
        idMaster: null,
        idUp: null,
        idDown: null,
        idLeft: null,
        idRight: null,
        idReserve1: null,
        idReserve2: null,
        idReserve3: null,
        p1: null,
        p2: null,
        del: null,
    },
];