export const textsDb = [
    {
        id: 1,
        name1: 'ПАРК ИСТОРИИ',
        name2: 'ВЕЛИКОЕ КНЯЖЕСТВО СУЛА',
        name3: '',
        fullName: '',
        slogan: 'ПОГРУЗИСЬ В ИСТОРИЮ',
        text: 'Лодки варяг и средневековые замки, королевская шляхетская ассамблея и очарование усадебной жизни – всё это представлено в программе «10 000 лет белорусской истории» и 20 музейных интерактивных экспозициях Парка истории Сула.',
        comment1: '',
        comment2: '',
        comment3: '',
        linkImg: '1.jpg',
        linkVideo: 'https://www.youtube.com/embed/uvSwHcEYz4s',
    },
    {
        id: 2,
        name1: 'ЗАМОК',
        name2: 'ЗАПОЛЬСКИЙ',
        name3: '',
        fullName: '',
        slogan: 'ВКЛ - СТРАНА ЗАМКОВ!',
        text: 'За всю многолетнюю историю количество возведенных дворцовых и замковых сооружений превысило сотню – не удивительно, что Беларусь называют "страной замков".',
        comment1: 'Уникальные достопримечательности, овеянные мифами и легендами, впечатляющие туристов своей архитектурой, – от древних оборонительных памятников XIV столетия до изысканных готических строений – в специальной подборке замков и дворцов Беларуси!',
        comment2: 'lorem lorem lorem lorem lorem lorem lorem lorem loremlorem lorem',
        comment3: 'lorem lorem lorem lorem lorem lorem lorem lorem loremlorem lorem',
        linkImg: '2.jpg',
        linkVideo: 'https://www.youtube.com/embed/uvSwHcEYz4s',
    },
    {
        id: 3,
        name1: 'ЗАМКИ',
        name2: 'БЕЛАРУСИ',
        name3: '',
        fullName: '',
        slogan: 'ВКЛ - СТРАНА ЗАМКОВ!',
        text: 'Замечательный художник-иллюстратор павел татарников в меличайших подробностях восстановил в своих работах внешний вид и атмосферу всех беларусских замков',
        comment1: 'lorem lorem lorem lorem lorem lorem lorem lorem loremlorem lorem',
        comment2: 'lorem lorem lorem lorem lorem lorem lorem lorem loremlorem lorem',
        comment3: 'lorem lorem lorem lorem lorem lorem lorem lorem loremlorem lorem',
        linkImg: '3.jpg',
        linkVideo: '',
    },
    {
        id: 4,
        name1: 'СУЛЬСКАЯ',
        name2: 'КУЗНЯ',
        name3: '',
        fullName: '',
        slogan: 'КУЙ ЖЕЛЕЗО',
        text: 'Ку́зница или кузня — мастерская, в которой производится ручная обработка металла, как правило, ковкой. Обязательно включала в себя очаг и наковальню.',
        comment1: '',
        comment2: '',
        comment3: '',
        linkImg: '4.jpg',
        linkVideo: '',
    },
    {
        id: 5,
        name1: 'КОЛЛЕГИУМ',
        name2: '',
        name3: '',
        fullName: '',
        slogan: 'ПРОСВЕЩЕНИЕ - МУЖЕСТВО!',
        text: 'Колле́гиум — иезуитское закрытое среднее учебное заведение. Появились в Европе в XVI веке.',
        comment1: 'Просвеще́ние — передача, распространение знаний и культуры, а также и система воспитательно-образовательных мероприятий и учреждений в каком-либо государстве; система культурно-просветительных мероприятий и специальных учреждений страны.',
        comment2: '',
        comment3: '',
        linkImg: '5.jpg',
        linkVideo: '',
    },
    {
        id: null,
        name1: '',
        name2: '',
        name3: '',
        fullName: '',
        slogan: '',
        text: '',
        comment1: '',
        comment2: '',
        comment3: '',
        linkImg: '',
        linkVideo: '',
    },
];